name: Verify MkDocs Build on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and Dependencies
        run: pip install -r docs/requirements.txt

      - name: Verify MkDocs build
        run: mkdocs build --strict