name: Verify Zensical Build on PR

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Zensical and Dependencies
        run: pip install -r docs/requirements.txt

      - name: Verify Zensical build
        run: zensical build --clean